id: 4150810970284eb78aba3b3776e5c730
initial_creation_type: ocr
source_metadata:
  volumes:
    3f5f9d7c14854987b6473dd057043137:
      base_file: v038.txt
      image_group_id: I1PD95883
      title: འཕགས་མ་རིག་པ་ཆེན་མོ་སོ་སོར་འབྲང་མའི་འཁོར་ལོ།
      total_pages: 1044
      volume_number: 38
